CUDA_VISIBLE_DEVICES=$1 python train.py \
    --batch_size=10 \
    --n_input_channel=256 \
    --n_input_size=64 \
    --epoch=100 \
    --tb_file=/data3/wuxiaolei/tb/final_cross \
    --sub_file=/StyleFormer_sigmoid \
    --resume \
    --clw=60 \
    --tvw=0 \
    --slw=1  \
    --alpha=1 \
    --spatial_bin=16 \
    --luma_bins=4 \
    --selection=Ax+b
