CUDA_VISIBLE_DEVICES=$1 python test.py \
    --trained_network=./output/StyleFormer_sigmoid/checkpoints/gen_00794001.pt \
    --input_path=/data/dataset/wuxiaolei/test_dataset/new9/content/ \
    --style_path=/data/dataset/wuxiaolei/test_dataset/new9/style/ \
    --output_path=newnewnew9 \
    --spatial_bin=16 \
    --alpha=0.8 \
    --selection=Ax+b \
    --luma_bins=4 \
    --results_path=./tv1
    #--style_path=/data1/wuxiaolei/project/grid_exp/grid_cross_final/style
